---
- name: Jenkins Installation Demo
  hosts: slave2
  gather_facts: true

  tasks:
    - name: Run apt-get update 
      apt:
        update_cache: yes

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - software-properties-common
        - apt-transport-https 
        - git


    - name: Add Java repository to ppa
      command: add-apt-repository ppa:openjdk-r/ppa -y

    - name: Install java
      apt:
        name: openjdk-8-jdk
        state: latest

    - name: Install GPG Key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present


    - name: Add apt repository to /etc/apt/sources.list
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present


    - name: Run apt-get update
      apt:
        update_cache: yes

    - name: Update repositories cache and install "jenkins" package
      apt:
        name: jenkins
        update_cache: yes


    - name: Install Jenkins
      apt:
        name: jenkins
        state: latest

    - name: get ansible initial admin password
      command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: key

    - name: show key contents
      debug:
        var: key.stdout


